### ISSUE TITLE
I made a cps system png

### ISSUE THREAD

**Issue by jaildesigner** [anthonycaccese/art-book-next-es-de#1]
Hi. CPS system did not have an image, so i made one. I hope you like it.
![cps](https://user-images.githubusercontent.com/7701662/208828082-7f7aa90c-1b67-41e8-b147-299f1f5994d4.png)

As a suggestion, I think all system images should be pixel perfect, with no interpolation.

Great theme!

**Comment by anthonycaccese** [comment]
wow this looks great!  I will add it now, thank you.  If you see any others that you would like to change please reach out.
