### ISSUE TITLE
[REQ] Displays Boxart option

### ISSUE THREAD

**Issue by illando** [anthonycaccese/art-book-next-es-de#14]
Hello Anthony,
thanks a lot for this beautiful theme! I really love it!
I have just a small request:
would be possible to add a Displays Boxart option in the gamelist view please?

Thanks in advance.

**Comment by anthonycaccese** [comment]
yes, i am refactoring the variants a bit now and am considering adding a direct variant for boxart

**Comment by illando** [comment]
That's great!!
Would you be so kind to left a comment here when this improvement will be done?
Thanks a lot!

**Comment by anthonycaccese** [comment]
work in progress:
<img width="752" alt="Screenshot 2024-04-14 at 10 31 37 AM" src="https://github.com/anthonycaccese/art-book-next-es-de/assets/1454947/bb50f518-af88-4bc5-8671-018667a71972">
<img width="752" alt="Screenshot 2024-04-14 at 10 32 06 AM" src="https://github.com/anthonycaccese/art-book-next-es-de/assets/1454947/b7bb1e8a-8e0f-42f0-a455-b10878738601">

I have a lot more work to do for other aspect ratios but getting there =)

**Comment by anthonycaccese** [comment]
16:9 coming together
<img width="1392" alt="Screenshot 2024-04-19 at 4 18 07 PM" src="https://github.com/anthonycaccese/art-book-next-es-de/assets/1454947/595c0e00-41c0-4b8d-89d6-b3831fa9659a">

**Comment by illando** [comment]
That's great @anthonycaccese!!!

**Comment by anthonycaccese** [comment]
Awesome and as of this morning these changes are available now when you get the latest version from the theme downloader.

The new variants for boxart only are called:
- List: Boxart
- [Help Off] List: Boxart

**Comment by illando** [comment]
@anthonycaccese Yeah!!!
Would be possible to set a different variant for some system?
For example I prefer to have screenshot image for MAME instead of Boxart.

Thanks.

**Comment by anthonycaccese** [comment]
sorry that is not possible in the engine
