### ISSUE TITLE
Theme Color Black and Greyscale

### ISSUE THREAD

**Issue by LordlRayden** [anthonycaccese/art-book-next-es-de#15]
Hey there,
with the latest version the black and grey color schemes disappeared, while still being mentioned under Configuration Options. Are there any plans to add them back? I really love the black scheme with the oled steam deck. 
Anyway, I love your theme and keep up the good work!

**Comment by anthonycaccese** [comment]
I was trying a test to see if they were used as I like to refactor from time to time to make things easier to maintain (sadly there are no direct metrics in place to track direct usage).  

Yes easy to add back in - will do that today.  Thank you for writing.

**Comment by anthonycaccese** [comment]
Hi just a heads up on a recent update.  I just synced the color schemes between all the versions of Art Book Next.  The black color scheme has been renamed to oled and I also replaced the grayscale color scheme with a new DMG focused one.

**Comment by LordlRayden** [comment]
Good stuff, thanks for the update! The DMG one looks interesting, but for me, nothing can beat the slick and clean look of the oled scheme, which makes the miximage really pop.
