### ISSUE TITLE
[REQUEST] Grid View

### ISSUE THREAD

**Issue by devanteweary** [anthonycaccese/art-book-next-es-de#18]
Hello! 

Let me say my FAVORITE ES-DE theme!!!!!!  
Goes with a handheld (in my case, Retroid Pocket 4 Pro) perfectly.  
Actually enhances the experience.

Anyway, I've been messing around with the theme files trying to get a grid view (with no help) working and thought I'd go straight to the source...

Do you think you could add a grid view to this with box art listed rather than a list view??

That would be awesome!!!

Thanks for reading!

- Devante

**Comment by anthonycaccese** [comment]
its something i would consider if i came up with a design or saw design i wanted to try building :)

the big consideration for the theme is aspect ratio support and what information to represent in a grid.  haven't yet spent much time on design ideas yet but open to looking at some as a start
