### ISSUE TITLE
[Feature Request]Show Count of Roms in the System View

### ISSUE THREAD

**Issue by erispyu** [anthonycaccese/art-book-next-es-de#21]
HI, is there anyway to support showing count of roms in the system view page? Some other ES-DE theme can do this, and I've found a Reddit thread, to manually support this by copying some xml files. https://www.reddit.com/r/SBCGaming/comments/1cy4h4k/art_book_next_theme_display_system_total_games/

**Comment by anthonycaccese** [comment]
Thank you but system count is not something I am interested in adding at this time.  I do appreciate you asking about it, if I work out a design I Iike for it in the future I'll add it in.
