### ISSUE TITLE
update the one for retropie

### ISSUE THREAD

**Issue by Exarkuniv** [anthonycaccese/art-book-next-es-de#4]
not really a issue, just seeing if you will ever updating the one for retro pie with some of the upgrades that you have on the other systems

or is that out of the scope for retropie since it uses a different version of  ES

either way, i love your themes and will use them anyway i can

**Comment by anthonycaccese** [comment]
sorry to say, the upgrades I have made to this es-de version won't be ported back to the retropie version.  The theme engine is very different and ES-DE's engine enabled the build of the new features.

**Comment by Exarkuniv** [comment]
Bummer. 
Wish RP would update the ES they use.

Thanks for the answer.
