### ISSUE TITLE
Cannot set screenshots for system view

### ISSUE THREAD

**Issue by f00tf00t** [anthonycaccese/art-book-next-es-de#5]
The fallback to screenshots/fanarts seems to have stopped working with the new update

![screenshot](https://github.com/anthonycaccese/art-book-next-es-de/assets/71181157/0bd56e76-917b-469d-ac6f-e9aa72020e4a)

I went into "_inc\systems" and just removed all background images, restarted es-de and the screenshots would show now, its just the void space "space.png"

When possible can advise be given on how to correc this @anthonycaccese ?

Thank you

**Comment by anthonycaccese** [comment]
Hi @f00tf00t that fallback functionality had to be removed as I am working on a refactor of the system view.  I don't know if i'll be able to add that back in with the changes I needed to make.  Will keep this open though to explore it in the future.
