### ISSUE TITLE
1:1 Resolution?

### ISSUE THREAD

**Issue by ghostcart** [anthonycaccese/art-book-next-es-de#9]
Would it be possible to add 1:1 resolution to the options?
It's a highly requested theme for ArkOS on RGB30.

Thank you.

**Comment by anthonycaccese** [comment]
Does ArkOS use ES-DE as a frontend? (from my knowledge it does not - it uses a different fork of EmulationStation)  If not this version of the theme will not work.  

The version for Batocera/JELOS has 1:1 resolution support and I can port it into this version but if ArkOS does not use ES-DE it will not work.

**Comment by anthonycaccese** [comment]
closing this for now - if you have additional information please feel free to comment with details.
